services:
  api:
    build: .
    networks:
      - public
      - iso
    ports:
      - 8000:8000

    command: gunicorn --bind 0.0.0.0:8000 api:app

  agent:
    build: .
    develop:
      watch:
        - action: sync
          path: ./Log_paths
          target: /app/Log_paths
    networks:
      - iso
    volumes:
      - ./Configuration_Files:/app/Configuration_Files:rw
    env_file:
      - .env
    depends_on:
      - api


    command: sleep infinity

networks:
  iso:
    internal: true
  public:


