services:
  api:
    build: .
    networks:
      - public
      - iso
    ports:
      - 8000:8000

    command: gunicorn --bind 0.0.0.0:8000 api:app

  agent:
    build: .
    networks:
      - iso
    volumes:
      - ./Log_paths:/app/Log_paths:ro
    env_file:
      - .env
    depends_on:
      - api
    
    command: sh -c "minicli -l && minicli -o"

networks:
  iso:
    internal: true
  public:


